TodoListApp.WebApp/Models/CompleteEditorViewModel.cs
namespace TodoListApp.WebApp.Models
{
    /// <summary>
    /// Represents the view model for the complete editor, including title and method details.
    /// </summary>
    public class CompleteEditorViewModel
    {
        /// <summary>
        /// Gets or sets the title displayed in the complete editor.
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// Gets or sets the method name associated with the complete editor action.
        /// </summary>
        public string? Method { get; set; }
    }
}

TodoListApp.WebApp/Components/ListsSideBarViewComponent.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using TodoListApp.WebApi.Models;
using TodoListApp.WebApp.Services.Interfaces;

namespace TodoListApp.WebApp.Components
{
    /// <summary>
    /// A view component that retrieves and displays the user's to-do lists in the sidebar.
    /// </summary>
    public class ListsSideBarViewComponent : ViewComponent
    {
        private readonly ITodoListWebApiService apiService;

        /// <summary>
        /// Initializes a new instance of the <see cref="ListsSideBarViewComponent"/> class.
        /// </summary>
        /// <param name="service">The service used to fetch the to-do list data.</param>
        public ListsSideBarViewComponent(ITodoListWebApiService service)
        {
            this.apiService = service;
        }

        /// <summary>
        /// Retrieves the user's to-do lists and returns the view with the list of to-do lists.
        /// </summary>
        /// <returns>A view component result with the list of to-do lists.</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = this.User as ClaimsPrincipal;
            var userId = user?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (user == null)
            {
                return this.View(new List<TodoListDto>());
            }

            var list = await this.apiService.GetAllAsync(userId!);
            return this.View(list);
        }
    }
}

TodoListApp.WebApp/Controllers/TagController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using TodoListApp.WebApi.Models;
using TodoListApp.WebApi.Models.DTO.UpdateDTO;
using TodoListApp.WebApi.Models.Logging;
using TodoListApp.WebApp.Services.Interfaces;

namespace TodoListApp.WebApp.Controllers
{
    /// <summary>
    /// Controller for managing tags associated with tasks.
    /// </summary>
    [Route("tag")]
    public class TagController : Controller
    {
        private readonly ITagWebApiService apiService;
        private readonly ILogger logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="TagController"/> class.
        /// </summary>
        /// <param name="apiService">Service for interacting with the tag-related API.</param>
        /// <param name="logger">Logger for logging activities within the controller.</param>
        public TagController(ITagWebApiService apiService, ILogger<TagController> logger)
        {
            this.apiService = apiService;
            this.logger = logger;
        }

        /// <summary>
        /// Displays the tag management menu.
        /// Retrieves all tags associated with the current user and returns them to the view.
        /// </summary>
        /// <param name="returnUrl">The URL to return to after completing the action.</param>
        /// <returns>The view displaying the tag menu with the list of tags.</returns>
        [HttpGet]
        [Route("TagMenu")]
        public async Task<IActionResult> TagMenu(Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.TagMenu));

            var user = this.User;
            var userId = user?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (user == null)
            {
                return this.View(new List<TodoListDto>());
            }

            var list = await this.apiService.GetAllAsync(userId!, userId!);

            _ = this.Ok(list);
            return this.View((list, returnUrl));
        }

        /// <summary>
        /// Creates a new tag.
        /// </summary>
        /// <param name="tag">The tag information to be added.</param>
        /// <param name="returnUrl">The URL to return to after completing the action.</param>
        /// <returns>A redirection to the specified return URL after the tag is created.</returns>
        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> Create(TagDto tag, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Create));

            if (this.ModelState.IsValid)
            {
                _ = await this.apiService.AddAsync(tag);
            }

            foreach (var error in this.ModelState.Values.SelectMany(v => v.Errors))
            {
                Console.WriteLine(error.ErrorMessage);
            }

            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }

        /// <summary>
        /// Updates an existing tag by its ID.
        /// </summary>
        /// <param name="tag">The updated tag information.</param>
        /// <param name="id">The ID of the tag to be updated.</param>
        /// <param name="returnUrl">The URL to return to after completing the action.</param>
        /// <returns>A redirection to the specified return URL after the tag is updated.</returns>
        [HttpPost]
        [Route("edit/{id:int}")]
        public async Task<IActionResult> Update(TagUpdateDto tag, int id, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Update));

            if (this.ModelState.IsValid)
            {
                this.logger.LogTrace("Invalid ModelState");

                _ = await this.apiService.UpdateAsync(tag, id);
            }

            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }

        /// <summary>
        /// Deletes a tag by its ID.
        /// </summary>
        /// <param name="id">The ID of the tag to be deleted.</param>
        /// <param name="returnUrl">The URL to return to after completing the action.</param>
        /// <returns>A redirection to the specified return URL after the tag is deleted.</returns>
        [HttpGet]
        [Route("delete")]
        public async Task<IActionResult> Delete(int id, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Delete));

            _ = await this.apiService.DeleteAsync(id);
            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }
    }
}

TodoListApp.WebApp/Controllers/TaskController.cs
using System.Globalization;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TodoListApp.DataAccess.Filters;
using TodoListApp.DataAccess.Filters.Enums;
using TodoListApp.WebApi.Models;
using TodoListApp.WebApi.Models.DTO.UpdateDTO;
using TodoListApp.WebApi.Models.Enums;
using TodoListApp.WebApi.Models.Logging;
using TodoListApp.WebApp.Models;
using TodoListApp.WebApp.Services.Interfaces;

namespace TodoListApp.WebApp.Controllers
{
    /// <summary>
    /// Controller for handling task-related operations in the web application.
    /// </summary>
    [Route("task")]
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ITaskWebApiService apiService;
        private readonly ILogger logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskController"/> class.
        /// </summary>
        /// <param name="apiService">Service for interacting with task Web API.</param>
        /// <param name="logger">Logger instance.</param>
        public TaskController(ITaskWebApiService apiService, ILogger<TaskController> logger)
        {
            this.apiService = apiService;
            this.logger = logger;
        }

        /// <summary>
        /// Displays the search view for tasks.
        /// </summary>
        /// <returns>The search view.</returns>
        [HttpGet("Search")]
        public IActionResult Search()
        {
            this.logger.LogTrace(nameof(this.Search));
            return this.View();
        }

        /// <summary>
        /// Searches for tasks based on the specified query and criteria.
        /// </summary>
        /// <param name="query">The search query.</param>
        /// <param name="searchBy">The field to search by.</param>
        /// <param name="page">Page number for pagination.</param>
        /// <returns>The search results view.</returns>
        [HttpGet]
        public async Task<IActionResult> SearchBy(string query, string searchBy, int page = 1)
        {
            this.logger.LogTrace(nameof(this.SearchBy));

            var assigneeId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
            TaskFilter filter = new TaskFilter()
            {
                PageNumber = page,
                AssigneeId = assigneeId,
                OwnerId = assigneeId,
            };

            DateTime date;
            switch (searchBy)
            {
                case "Title": filter.TextInTitle = query; break;
                case "DueDate":
                    if (DateTime.TryParseExact(query, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
                    {
                        filter.DueDate = date;
                    }

                    break;
                case "CreationDate":
                    if (DateTime.TryParseExact(query, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
                    {
                        filter.CreationDate = date;
                    }

                    break;
                default:
                    break;
            }

            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View("Search", new SearchViewModel()
            {
                Query = query,
                SearchBy = searchBy,
                TaskPagging = list,
            });
        }

        /// <summary>
        /// Retrieves all tasks belonging to a specific list.
        /// </summary>
        /// <param name="listId">ID of the list.</param>
        /// <param name="page">Page number for pagination.</param>
        /// <returns>The task list view.</returns>
        [HttpGet("Get")]
        public async Task<IActionResult> GetAllTasksByListId(int listId, int page = 1)
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByListId));

            TaskFilter filter = new TaskFilter()
            {
                TodoListId = listId,
                PageNumber = page,
            };
            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View((list, listId));
        }

        /// <summary>
        /// Retrieves all tasks filtered by a tag.
        /// </summary>
        /// <param name="tag">The tag to filter by.</param>
        /// <param name="page">Page number for pagination.</param>
        /// <returns>The view with filtered tasks.</returns>
        [HttpGet("GetByTag")]
        public async Task<IActionResult> GetAllTasksByTag(string tag, int page = 1)
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByTag));

            TaskFilter filter = new TaskFilter()
            {
                TagName = tag,
                PageNumber = page,
            };
            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View((list, tag));
        }

        /// <summary>
        /// Retrieves all tasks assigned to the current user.
        /// </summary>
        /// <returns>The view with tasks assigned to the user.</returns>
        [HttpGet("GetByAssignee")]
        public async Task<IActionResult> GetAllTasksByAssigneeId()
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByAssigneeId));

            var assigneeId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
            TaskFilter filter = new TaskFilter()
            {
                AssigneeId = assigneeId,
                Overdue = Overdue.Active,
            };
            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View((list, assigneeId));
        }

        /// <summary>
        /// Stores the provided filter in the session and redirects to filtered results.
        /// </summary>
        /// <param name="filter">Task filter to apply.</param>
        /// <param name="returnUrl">URL to return to after applying filter.</param>
        /// <returns>Redirection to filtered results view.</returns>
        [HttpPost("GetByFilter")]
        public IActionResult GetAllTasksByFilter(TaskFilter filter, Uri returnUrl = default!)
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByFilter));

            this.HttpContext.Session.SetString("filter", JsonSerializer.Serialize(filter));
            return this.RedirectToAction("FilteredResults", new { returnUrl });
        }

        /// <summary>
        /// Displays results based on a previously stored filter.
        /// </summary>
        /// <param name="returnUrl">URL to return to if filter is missing.</param>
        /// <returns>The filtered results view.</returns>
        [HttpGet("FilteredResults")]
        public async Task<IActionResult> FilteredResults(Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.FilteredResults));

            var filterJson = this.HttpContext.Session.GetString("filter");
            if (!string.IsNullOrEmpty(filterJson))
            {
                var filter = JsonSerializer.Deserialize<TaskFilter>(filterJson);
                var list = await this.apiService.GetAllByFilterAsync(filter!);
                return this.View("FilteredResults", (list, filter));
            }

            this.logger.LogWarning("Json is null or empty");
            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }

        /// <summary>
        /// Marks a task as complete with a given status.
        /// </summary>
        /// <param name="id">Task ID.</param>
        /// <param name="status">New status for the task.</param>
        /// <param name="returnUrl">URL to return to after update.</param>
        /// <returns>Redirection to returnUrl.</returns>
        [HttpPost("complete")]
        public IActionResult TaskComplete(int id, Status status, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.TaskComplete));

            TaskUpdateDto model = new TaskUpdateDto()
            {
                Status = status,
            };
            _ = this.apiService.UpdateAsync(model, id);
            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }

        /// <summary>
        /// Displays the edit form for a task.
        /// </summary>
        /// <param name="taskId">Task ID to edit.</param>
        /// <param name="returnUrl">URL to return to after editing.</param>
        /// <returns>The edit view.</returns>
        [HttpGet]
        [Route("edit/{taskId:int}")]
        public async Task<IActionResult> Edit(int taskId, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Edit));

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
            var ownerId = await this.apiService.GetTaskOwnerId(taskId);
            if (userId != ownerId)
            {
                this.logger.LogWarning("User id don't equal owner id");
                return this.View("NoPermission", "edit this task");
            }

            var task = await this.apiService.GetByIdAsync(taskId);
            return this.View((task, returnUrl));
        }

        /// <summary>
        /// Updates the task with new values.
        /// </summary>
        /// <param name="task">Updated task model.</param>
        /// <param name="id">Task ID.</param>
        /// <param name="returnUrl">URL to return to.</param>
        /// <returns>The result view or the edit form with validation errors.</returns>
        [HttpPost]
        [Route("edit/{id:int}")]
        public async Task<IActionResult> Update(TaskUpdateDto task, int id, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Update));

            if (task == null)
            {

TodoListApp.WebApp/Views/Shared/CompleteEditor.cshtml
@model CompleteEditorViewModel

@{
    Layout = "_MinimalLayout";
}

<div class="text-center" style="margin-top: 30vh">
    <h2>Success!</h2>
    <p>@Model.Title have been successfuly @Model.Method</p>
    <p>Now you can find it in corresponding To-do List</p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Main menu</a>
</div>

TodoListApp.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>To-do app</title>
    <link href="/lib/bootstrap-5.2.3-dist/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        .wrapper {
            height: 100%;
            display: flex;
            flex-direction: column;
        }

        main {
            flex: 1;
            display: flex;
            overflow: hidden;
        }

        .sidebar-wrapper {
            display: flex;
            flex-direction: column;
            height: calc(100vh - 112px); /* учитываем высоту header */
        }

        .sidebar {
            display: flex;
            flex-direction: column;
            width: 380px;
            height: 107%;
            overflow: hidden;
        }

        .sidebar-container {
            flex-grow: 1;
            overflow-x: hidden;
            overflow-y: auto;
        }

        .main-content {
            flex-grow: 1;
            overflow: auto;
        }

        /* Toggle sidebar visibility via checkbox */
        #sidebarToggle:checked ~ .wrapper main .sidebar-wrapper .sidebar {
            display: none !important;
        }

        #sidebarToggle:checked ~ .wrapper main .main-content {
            flex-grow: 1;
            margin-left: 0;
        }

        /* Responsive adjustments */
        @@media (max-width: 768px) {
            .sidebar

        {
            width: 200px;
        }

        }

        @@media (max-width: 576px) {
            .sidebar

        {
            display: none;
        }

        .main-content {
            margin-left: 0;
        }

        }
    </style>
</head>
<body>
    <input type="checkbox" id="sidebarToggle" hidden />

    <div class="wrapper">
        <!-- HEADER -->
        <header>
            <partial name="_Navbar" />
        </header>

        <!-- MAIN -->
        <main>
            <!-- SIDEBAR -->
            <div class="sidebar-wrapper">
                
                <div class="sidebar bg-dark text-white d-flex flex-column align-items-stretch flex-shrink-0">
                        
                            @await Component.InvokeAsync("ListsSideBar")
                </div>
            </div>

            <!-- MAIN CONTENT -->
            <div class="main-content m-1 p-1">
                <div class="col-12">
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>
    <partial name="_ValidationScriptsPartial"/>
</body>
</html>

TodoListApp.WebApp/Views/Shared/_MinimalLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>To-do app</title>
    <link href="/lib/bootstrap-5.2.3-dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <partial name="_ValidationScriptsPartial" />

    @RenderSection("Scripts", required: false) 

</body>
</html>
<style>
    html, body {
        height: 100%;
        background-color: #fcfcfc;
    }
</style>

TodoListApp.WebApp/Views/Shared/_NavLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>To-do app</title>
    <link href="/lib/bootstrap-5.2.3-dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        html, body {
            height: 100%;
            background-color: #fcfcfc;
            overflow-x: hidden;
        }
    </style>
</head>
<body>
    <div>
        <partial name="_Navbar" />
    </div>
    <div>
        @RenderBody()
    </div>

    <partial name="_ValidationScriptsPartial" />

    @RenderSection("Scripts", required: false)

</body>
</html>

TodoListApp.WebApp/Views/Shared/_Navbar.cshtml
<nav class="navbar sticky-top navbar-expand-sm navbar-light bg-white border-bottom shadow-sm mb-3">
    <div class="container">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">To-do list app</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse container-xxl navbar-collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-action="Index" asp-controller="Home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Task" asp-action="GetAllTasksByAssigneeId">Current tasks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Tag" asp-action="TagMenu" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">Tags</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Task" asp-action="Search">Search</a>
                </li>

            </ul>
            <a class ="nav-link text-dark px-3" asp-action="LogOut" asp-controller="Auth">Log out</a>
            <a class ="nav-link text-dark" asp-action="Profile" asp-controller="Home">Profile</a>
        </div>
    </div>
</nav>

TodoListApp.WebApp/Views/Shared/_TaskLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>To-do app</title>
    <link href="/lib/bootstrap-5.2.3-dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <partial name="_ValidationScriptsPartial" />

    @RenderSection("Scripts", required: false) 

</body>
</html>
<style>
    html, body {
        height: 100%;
        background-color: #fcfcfc;
    }
</style>

TodoListApp.WebApp/Views/Shared/_TodoListLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>To-do app</title>
    <link href="/lib/bootstrap-5.2.3-dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <partial name="_ValidationScriptsPartial" />

</body>
</html>
<style>
    html, body {
        height: 100%;
        background-color: #fcfcfc;
    }
</style>