TodoListApp.WebApp/Models/SearchViewModel.cs
using TodoListApp.WebApi.Models.DTO.PagingDTO;

namespace TodoListApp.WebApp.Models
{
    /// <summary>
    /// Represents the model for searching tasks, including pagination and search filters.
    /// </summary>
    public class SearchViewModel
    {
        /// <summary>
        /// Gets or sets the task pagination information.
        /// </summary>
        public TaskPaging? TaskPagging { get; set; }

        /// <summary>
        /// Gets or sets the search query string used to filter tasks.
        /// </summary>
        public string? Query { get; set; }

        /// <summary>
        /// Gets or sets the field by which tasks are being searched (e.g., title, description).
        /// </summary>
        public string? SearchBy { get; set; }
    }
}

TodoListApp.WebApp/Models/TaskEditorViewModel.cs
using TodoListApp.WebApi.Models;

namespace TodoListApp.WebApp.Models
{
    /// <summary>
    /// Represents the view model for editing tasks, extending from the <see cref="AbstractEditorViewModel"/>.
    /// </summary>
    public class TaskEditorViewModel : AbstractEditorViewModel
    {
        /// <summary>
        /// Gets or sets the task data for editing.
        /// </summary>
        public TaskDto Task { get; set; } = new TaskDto();

        /// <summary>
        /// Gets or sets the error message(s) associated with the task editing.
        /// </summary>
        public string? Errors { get; set; }
    }
}

TodoListApp.WebApp/Models/TaskViewModel.cs
using TodoListApp.WebApi.Models;

namespace TodoListApp.WebApp.Models
{
    /// <summary>
    /// Represents the view model for a task, including task details, comments, tags, owner information, and return URL.
    /// </summary>
    public class TaskViewModel
    {
        /// <summary>
        /// Gets or sets the task details.
        /// </summary>
        public TaskDto? Task { get; set; } = new TaskDto();

        /// <summary>
        /// Gets or sets the collection of comments associated with the task.
        /// </summary>
        public IEnumerable<CommentDto>? Comments { get; set; }

        /// <summary>
        /// Gets or sets the collection of tags associated with the task.
        /// </summary>
        public IEnumerable<TagDto>? Tags { get; set; }

        /// <summary>
        /// Gets or sets the return URL to navigate back after completing the action. Default is "/" (root URL).
        /// </summary>
        public Uri ReturnUrl { get; set; } = default!;

        /// <summary>
        /// Gets or sets the ID of the owner of the task.
        /// </summary>
        public string OwnerId { get; set; } = string.Empty;
    }
}

TodoListApp.WebApp/Controllers/DetailsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using TodoListApp.WebApi.Models.Logging;
using TodoListApp.WebApp.Infrastructure;

namespace TodoListApp.WebApp.Controllers
{
    /// <summary>
    /// Controller responsible for displaying task details.
    /// </summary>
    [Route("details")]
    public class DetailsController : Controller
    {
        private readonly TaskAggregatorService service;
        private readonly ILogger logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="DetailsController"/> class.
        /// </summary>
        /// <param name="service">The service used to aggregate task details.</param>
        /// <param name="logger">Logger instance for logging actions and errors.</param>
        public DetailsController(TaskAggregatorService service, ILogger<DetailsController> logger)
        {
            this.service = service;
            this.logger = logger;
        }

        /// <summary>
        /// Displays detailed information for a specific task.
        /// </summary>
        /// <param name="id">The ID of the task to fetch details for.</param>
        /// <param name="returnUrl">The URL to which the user should be redirected if the task is not found.</param>
        /// <returns>The view displaying task details if found, otherwise redirects to the returnUrl.</returns>
        [Route("task")]
        public async Task<IActionResult> TaskDetails(int id, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.TaskDetails));

            var model = await this.service.AggregateTask(id);

            if (model == null)
            {
                if (returnUrl != null)
                {
                    return this.Redirect(returnUrl.ToString());
                }

                return this.Redirect("~/Home/Index");
            }

            model.ReturnUrl = returnUrl;

            var ownerId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;

            return this.View((model, ownerId == model.OwnerId));
        }
    }
}

TodoListApp.WebApp/Controllers/TaskController.cs
using System.Globalization;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TodoListApp.DataAccess.Filters;
using TodoListApp.DataAccess.Filters.Enums;
using TodoListApp.WebApi.Models;
using TodoListApp.WebApi.Models.DTO.UpdateDTO;
using TodoListApp.WebApi.Models.Enums;
using TodoListApp.WebApi.Models.Logging;
using TodoListApp.WebApp.Models;
using TodoListApp.WebApp.Services.Interfaces;

namespace TodoListApp.WebApp.Controllers
{
    /// <summary>
    /// Controller for handling task-related operations in the web application.
    /// </summary>
    [Route("task")]
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ITaskWebApiService apiService;
        private readonly ILogger logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskController"/> class.
        /// </summary>
        /// <param name="apiService">Service for interacting with task Web API.</param>
        /// <param name="logger">Logger instance.</param>
        public TaskController(ITaskWebApiService apiService, ILogger<TaskController> logger)
        {
            this.apiService = apiService;
            this.logger = logger;
        }

        /// <summary>
        /// Displays the search view for tasks.
        /// </summary>
        /// <returns>The search view.</returns>
        [HttpGet("Search")]
        public IActionResult Search()
        {
            this.logger.LogTrace(nameof(this.Search));
            return this.View();
        }

        /// <summary>
        /// Searches for tasks based on the specified query and criteria.
        /// </summary>
        /// <param name="query">The search query.</param>
        /// <param name="searchBy">The field to search by.</param>
        /// <param name="page">Page number for pagination.</param>
        /// <returns>The search results view.</returns>
        [HttpGet]
        public async Task<IActionResult> SearchBy(string query, string searchBy, int page = 1)
        {
            this.logger.LogTrace(nameof(this.SearchBy));

            var assigneeId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
            TaskFilter filter = new TaskFilter()
            {
                PageNumber = page,
                AssigneeId = assigneeId,
                OwnerId = assigneeId,
            };

            DateTime date;
            switch (searchBy)
            {
                case "Title": filter.TextInTitle = query; break;
                case "DueDate":
                    if (DateTime.TryParseExact(query, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
                    {
                        filter.DueDate = date;
                    }

                    break;
                case "CreationDate":
                    if (DateTime.TryParseExact(query, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
                    {
                        filter.CreationDate = date;
                    }

                    break;
                default:
                    break;
            }

            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View("Search", new SearchViewModel()
            {
                Query = query,
                SearchBy = searchBy,
                TaskPagging = list,
            });
        }

        /// <summary>
        /// Retrieves all tasks belonging to a specific list.
        /// </summary>
        /// <param name="listId">ID of the list.</param>
        /// <param name="page">Page number for pagination.</param>
        /// <returns>The task list view.</returns>
        [HttpGet("Get")]
        public async Task<IActionResult> GetAllTasksByListId(int listId, int page = 1)
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByListId));

            TaskFilter filter = new TaskFilter()
            {
                TodoListId = listId,
                PageNumber = page,
            };
            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View((list, listId));
        }

        /// <summary>
        /// Retrieves all tasks filtered by a tag.
        /// </summary>
        /// <param name="tag">The tag to filter by.</param>
        /// <param name="page">Page number for pagination.</param>
        /// <returns>The view with filtered tasks.</returns>
        [HttpGet("GetByTag")]
        public async Task<IActionResult> GetAllTasksByTag(string tag, int page = 1)
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByTag));

            TaskFilter filter = new TaskFilter()
            {
                TagName = tag,
                PageNumber = page,
            };
            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View((list, tag));
        }

        /// <summary>
        /// Retrieves all tasks assigned to the current user.
        /// </summary>
        /// <returns>The view with tasks assigned to the user.</returns>
        [HttpGet("GetByAssignee")]
        public async Task<IActionResult> GetAllTasksByAssigneeId()
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByAssigneeId));

            var assigneeId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
            TaskFilter filter = new TaskFilter()
            {
                AssigneeId = assigneeId,
                Overdue = Overdue.Active,
            };
            var list = await this.apiService.GetAllByFilterAsync(filter);
            return this.View((list, assigneeId));
        }

        /// <summary>
        /// Stores the provided filter in the session and redirects to filtered results.
        /// </summary>
        /// <param name="filter">Task filter to apply.</param>
        /// <param name="returnUrl">URL to return to after applying filter.</param>
        /// <returns>Redirection to filtered results view.</returns>
        [HttpPost("GetByFilter")]
        public IActionResult GetAllTasksByFilter(TaskFilter filter, Uri returnUrl = default!)
        {
            this.logger.LogTrace(nameof(this.GetAllTasksByFilter));

            this.HttpContext.Session.SetString("filter", JsonSerializer.Serialize(filter));
            return this.RedirectToAction("FilteredResults", new { returnUrl });
        }

        /// <summary>
        /// Displays results based on a previously stored filter.
        /// </summary>
        /// <param name="returnUrl">URL to return to if filter is missing.</param>
        /// <returns>The filtered results view.</returns>
        [HttpGet("FilteredResults")]
        public async Task<IActionResult> FilteredResults(Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.FilteredResults));

            var filterJson = this.HttpContext.Session.GetString("filter");
            if (!string.IsNullOrEmpty(filterJson))
            {
                var filter = JsonSerializer.Deserialize<TaskFilter>(filterJson);
                var list = await this.apiService.GetAllByFilterAsync(filter!);
                return this.View("FilteredResults", (list, filter));
            }

            this.logger.LogWarning("Json is null or empty");
            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }

        /// <summary>
        /// Marks a task as complete with a given status.
        /// </summary>
        /// <param name="id">Task ID.</param>
        /// <param name="status">New status for the task.</param>
        /// <param name="returnUrl">URL to return to after update.</param>
        /// <returns>Redirection to returnUrl.</returns>
        [HttpPost("complete")]
        public IActionResult TaskComplete(int id, Status status, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.TaskComplete));

            TaskUpdateDto model = new TaskUpdateDto()
            {
                Status = status,
            };
            _ = this.apiService.UpdateAsync(model, id);
            if (returnUrl != null)
            {
                return this.Redirect(returnUrl.ToString());
            }

            return this.Redirect("~/Home/Index");
        }

        /// <summary>
        /// Displays the edit form for a task.
        /// </summary>
        /// <param name="taskId">Task ID to edit.</param>
        /// <param name="returnUrl">URL to return to after editing.</param>
        /// <returns>The edit view.</returns>
        [HttpGet]
        [Route("edit/{taskId:int}")]
        public async Task<IActionResult> Edit(int taskId, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Edit));

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
            var ownerId = await this.apiService.GetTaskOwnerId(taskId);
            if (userId != ownerId)
            {
                this.logger.LogWarning("User id don't equal owner id");
                return this.View("NoPermission", "edit this task");
            }

            var task = await this.apiService.GetByIdAsync(taskId);
            return this.View((task, returnUrl));
        }

        /// <summary>
        /// Updates the task with new values.
        /// </summary>
        /// <param name="task">Updated task model.</param>
        /// <param name="id">Task ID.</param>
        /// <param name="returnUrl">URL to return to.</param>
        /// <returns>The result view or the edit form with validation errors.</returns>
        [HttpPost]
        [Route("edit/{id:int}")]
        public async Task<IActionResult> Update(TaskUpdateDto task, int id, Uri returnUrl)
        {
            this.logger.LogTrace(nameof(this.Update));

            if (task == null)
            {

TodoListApp.WebApp/Views/Task/Create.cshtml
@model (TaskDto Task, Uri ReturnUrl)
@{
    Layout = "_NavLayout";
}
<div class="container-sm">
    <partial name="_TaskEditor.cshtml" model='new TaskEditorViewModel()
{
    Task = @Model.Task,
    CallbackMethodName = "Create",
    ThemeColor = "warning",
    Title = "Create",
    ReturnUrl = @Model.ReturnUrl,
}' />
</div>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
  }

TodoListApp.WebApp/Views/Task/Edit.cshtml
@model (TaskDto task, Uri url)
@{
    Layout = "_MinimalLayout";
}
<div class="container">
<partial name ="_TaskEditor.cshtml" model='new TaskEditorViewModel()
{
    Task = @Model.task,
    CallbackMethodName = "Update",
    ThemeColor = "warning",
    Title = "Edit",
    ReturnUrl = @Model.url,
}'/>
</div>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
  }

TodoListApp.WebApp/Views/Task/FilteredResults.cshtml
    @model (TaskPaging taskPaging, TaskFilter filter);
    @{
        TaskFilter filter = Model.filter;
        TaskListPageViewModel listModel = new TaskListPageViewModel()
                {
                    AssigneeId = filter.AssigneeId,
                    List = Model.taskPaging.Items,
                    Title = "Assigned tasks",
                };
    }
    <partial name="_AssigneeNavigation.cshtml" model="@listModel" />
    <partial name="_TaskList.cshtml" model="@listModel"/>
    <div page-model-post="@Model.taskPaging" page-classes-enabled="true"
         class="btn-group pull-right m-1"
         page-post-TodoListId="@filter.TodoListId" page-post-AssigneeId="@filter.AssigneeId!"
         page-post-Overdue="@filter.Overdue!" page-post-PageSize="@filter.PageSize"
         page-post-SortBy="@filter.SortBy!"
         page-post-IsDescending="@filter.IsDescending" page-post-returnUrl="null!"
     page-action="GetByFilter"
     page-controller="Task">
    </div>  

TodoListApp.WebApp/Views/Task/GetAllTasksByAssigneeId.cshtml
@model (TaskPaging taskPaging, string assigneeId)
@{
    TaskListPageViewModel listModel = new TaskListPageViewModel()
            {
                AssigneeId = Model.assigneeId,
                List = Model.taskPaging.Items,
                Title = "Assigned tasks",
            };
}
<partial name="_AssigneeNavigation.cshtml" model="@listModel" />
<partial name="_TaskList.cshtml" model="@listModel"/>
<div page-model="@Model.taskPaging" page-classes-enabled="true"
     page-url-assigneeId="@Model.assigneeId" class="btn-group pull-right m-1">
</div>

TodoListApp.WebApp/Views/Task/GetAllTasksByFilter.cshtml
@model TaskPaging 
@{
    TaskListPageViewModel listModel = new TaskListPageViewModel()
            {
                AssigneeId = "admin",
                List = Model.Items,
                Title = "To-do list",
            };
}
<partial name="_TaskNavigation.cshtml" model="@listModel" />
<partial name="_TaskList.cshtml" model="@listModel"/>
@* <div page-model="@Model" page-classes-enabled="true" *@
@*      page-url-listId="@Model.id" class="btn-group pull-right m-1"> *@
@* </div> *@

TodoListApp.WebApp/Views/Task/GetAllTasksByListId.cshtml
@model (TaskPaging taskPaging, int id)
@{
    TaskListPageViewModel listModel = new TaskListPageViewModel()
            {
                AssigneeId = "admin",
                TodoListId = Model.id,
                List = Model.taskPaging.Items,
                Title = "To-do list",
            };
}
<partial name="_TaskNavigation.cshtml" model="@listModel" />
<partial name="_TaskList.cshtml" model="@listModel" />
<div page-model="@Model.taskPaging" page-classes-enabled="true"
     page-url-listId="@Model.id" class="btn-group pull-right m-1">
</div>

TodoListApp.WebApp/Views/Task/Search.cshtml
@model SearchViewModel?
@{
    Layout = "_MinimalLayout";
}
<partial name="_Navbar" />

<div class="container">
    <h3 class="text-black text-center p-1">All tags from to-do lists</h3>

    @if(Model != null)
    {
        <div class="container-fluid m-auto">
            <form class="d-flex" asp-action="SearchBy" asp-controller="Task" method="get" role="search" aria-label="Search criteria">

                <div style="max-width: 150px">
                    <select class="btn-secondary form-select me-2" name="searchBy">
                        <option value="Title" selected="@(Model.SearchBy == "Title")">Title</option>
                        <option value="CreationDate" selected="@(Model.SearchBy == "CreationDate")">Creation date</option>
                        <option value="DueDate" selected="@(Model.SearchBy == "DueDate")">Due date</option>
                    </select>
                </div>
                

                <input class="form-control me-2" type="search" name="query" value="@Model.Query"  aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>

        TaskListPageViewModel listModel = new TaskListPageViewModel()
                {
                    List = Model?.TaskPagging?.Items,
                };
        <partial name="_TaskList.cshtml" model="@listModel" />

        @switch (Model?.SearchBy)
        {
            case ("Title"):
                <div page-model="Model?.TaskPagging" page-classes-enabled="true"
                page-url-TextInTitle="@Model?.Query!" class="btn-group pull-right m-1">
                </div>
                break;
            case ("CreationDate"):
                <div page-model="Model?.TaskPagging" page-classes-enabled="true"
                page-url-CreationDate="@Model?.Query!" class="btn-group pull-right m-1">
                </div>
                break;
            case ("DueDate"):
                <div page-model="Model?.TaskPagging" page-classes-enabled="true"
                page-url-DueDate="@Model?.Query!" class="btn-group pull-right m-1">
                </div>
                break;
            default:
                <div page-model="Model?.TaskPagging" page-classes-enabled="true"
                class="btn-group pull-right m-1">
                </div>
                break;
        }

    }
    else
    {
        <div class="container">
            <div class="m-auto g-3" style="max-width: 600px;">
                <form class="d-flex" asp-action="SearchBy" asp-controller="Task" method="get" aria-label="Search criteria" role="search">

                    <div class="w-auto">
                        <select class=" btn-secondary form-select me-2" name="searchBy">
                            <option value="Title">Title</option>
                            <option value="CreationDate">Creation date</option>
                            <option value="DueDate">Due date</option>
                        </select>
                    </div>

                    <input class="form-control me-2" style="max-width: 500px" type="search" name="query" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
            
        </div>
    }

    @* <div class="form-group mt-3 text-center"> *@

    @*     <a class="btn btn-primary" type="submit" href="#">Back</a> *@
    @* </div> *@
</div>  

TodoListApp.WebApp/Views/Task/_TaskEditor.cshtml
@model TaskEditorViewModel
@{
    TaskDto task = Model.Task;
}

<h2 class="text-black text-center p-1">@Model.Title a Tasks</h2>

<div class="">
    <div class="m-auto g-3" style="max-width: 450px;">
        <form asp-action="@Model.CallbackMethodName"
              asp-controller="Task"
              asp-route-id="@(task?.Id != 0 ? task?.Id : null)"
              asp-route-returnUrl="@Model.ReturnUrl"
              method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @if (task?.Id != 0)
            {
                <div class="form-group">
                    <label for="Task_Id" class="control-label">Task ID</label>
                    <input asp-for="Task.Id" class="form-control" readonly id="Task_Id" />
                </div>
                <div class="form-group">
                    <label for="Task_DateCreated" class="control-label">Date Created</label>
                    <input asp-for="Task.DateCreated" class="form-control" readonly id="Task_DateCreated" />
                </div>
                <div class="form-group">
                    <label for="Task_Status" class="control-label">Status</label>
                    <select asp-for="Task.Status" class="form-control" id="Task_Status">
                        <option value="NotStarted">Not started</option>
                        <option value="InProgress">In progress</option>
                        <option value="Completed">Completed</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="Task_AssigneeId" class="control-label">Assignee ID</label>
                    <input asp-for="Task.AssigneeId" value="@task?.AssigneeId" class="form-control" id="Task_AssigneeId" />
                </div>
            }

            @if (task?.Id == 0)
            {
                <input type="hidden" asp-for="Task.AssigneeId" value="@task?.AssigneeId" />
                <input type="hidden" asp-for="Task.TodoListId" value="@task?.TodoListId" />
                <input type="hidden" asp-for="Task.Status" value="NotStarted" />
            }

            <div class="form-group">
                <label for="Task_Title" class="control-label">Title</label>
                <input asp-for="Task.Title" class="form-control" id="Task_Title" />
                <span asp-validation-for="Task.Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Task_Description" class="control-label">Description</label>
                <input asp-for="Task.Description" class="form-control" id="Task_Description" />
                <span asp-validation-for="Task.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Task_DueDate" class="control-label">Due Date</label>
                <input asp-for="Task.DueDate" class="form-control" id="Task_DueDate" />
                <span asp-validation-for="Task.DueDate" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 text-center">
                <button type="submit" class="btn btn-success">Save</button>
                <a class="btn btn-primary" href="@Model?.ReturnUrl">Back</a>
            </div>

        </form>
    </div>
</div>

TodoListApp.WebApp/Views/Task/_TaskList.cshtml
@model TaskListPageViewModel
<style>
    .dropdown:hover > .dropdown-menu {
    display: block;
    }

    .dropdown-menu .dropdown-menu {
    display: none;
    margin-left: 100%;
    top: 0;
    left: 0;
    }

    .dropdown-menu .dropdown:hover > .dropdown-menu {
    display: block;
    }
</style>

@if (Model.List == null)
{
    <div class="text-center">
        <h1 class="display-4">To-do list have no task yet</h1>
    </div>
}
else
{

    <div class="container">
        <div class="text-center">
            <h1 class="display-4">@Model.Title</h1>
        </div>
        @foreach (var task in @Model.List)
        {
            string color = "bg-dark";
            var overdue = DateTime.Compare(task.DueDate.GetValueOrDefault(), DateTime.Now);
            if (overdue < 0)
            {
                color = "bg-danger";
            }
            <div class="my-2 p-2 rounded shadow-sm @color  bg-opacity-10">
                <h6 class="border-bottom pb-2 mb-0 mx-2">@task.Title</h6>
                <div class="d-flex flex-column flex-md-row justify-content-between text-body-secondary pt-3">
                    <div class="d-flex">

                        <form id="@task?.Id" asp-controller="Task" asp-action="TaskComplete" method="post" asp-antiforgery="true">
                            <input type="hidden" name="id" value="@task?.Id" />
                            <input type="hidden" name="status" value="@(task?.Status == TodoListApp.WebApi.Models.Enums.Status.Completed ? TodoListApp.WebApi.Models.Enums.Status.InProgress : TodoListApp.WebApi.Models.Enums.Status.Completed)" />

                            @if (Model.ReturnUrl == null)
                            {
                                <input type="hidden" name="returnUrl"
                                value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                            }
                            else
                            {
                                <input type="hidden" name="returnUrl"
                                       value="@Model.ReturnUrl" />
                            }
                            <input type="checkbox" class="form-check-input me-1" onchange="this.form.submit()" @(task?.Status == TodoListApp.WebApi.Models.Enums.Status.Completed ? "checked" : "") />

                            
                        </form>

                        
                        <div style="word-wrap: break-word;" class="mx-1">
                            @task?.Description
                        </div>
                    </div>
                    <div class=" mb-2 mb-md-0">
                        <a class="btn btn-info btn-sm" asp-controller="Details" asp-action="TaskDetails" method="post" asp-route-id="@task?.Id" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                            Details
                        </a>
                        <a class="btn btn-warning btn-sm" asp-controller="Task" asp-action="Edit" method="post" asp-route-taskId="@task?.Id" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                            Edit
                        </a>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#modal_@task?.Id">
                            Delete
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="modal_@task?.Id" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalLabel_@task?.Id" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="modalLabel_@task?.Id">Do your really want to delete the task?</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        When you click "Delete" button this task with all details and comments will permanently removed
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <a class="btn btn-danger" asp-controller="Task" asp-action="Delete" asp-route-id="@task?.Id" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                                            Delete
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                
            </div>
        }
    </div>
}

TodoListApp.WebApp/Views/Task/_TaskNavigation.cshtml
@model TaskListPageViewModel


<nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom shadow-sm mb-3">
    <div class="container">
        <a class="navbar-brand" asp-controller="" asp-action="">@Model.Title</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                @if (Model.TodoListId != 0)
                {
                    <li class="nav-item">
                        <a class="btn btn-light" asp-controller="Task" asp-action="Create" asp-route-listId="@Model.TodoListId" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">
                            New task
                        </a>
                    </li>
                }

            </ul>
        </div>
    </div>
</nav>